title = "My Awesome Service"

[owner]
name = "Test User"
organization = "Test Org"
dob = 1979-05-27T07:32:00-08:00

[main_db]
host = "db.example.toml"
port = 5432
user = "toml_user"
# Require the password from environment; fail if MAIN_DB_PASSWORD is not set
password = "{{ requiredEnv \"MAIN_DB_PASSWORD\" }}"
database = "main_toml_db"

[replica_db]
host = "replica.db.example.toml"
port = 5432
user = "toml_user_ro"
# Use getenv here, allows empty password if not set (adjust logic if needed)
password = "{{ getenv \"REPLICA_DB_PASSWORD\" }}"
database = "main_toml_db"

[servers]
  [servers.alpha]
  ip = "10.0.0.1"
  role = "frontend"
  [servers.beta]
  ip = "10.0.0.2"
  role = "backend"

[logging]
level = "warn"
rotation_days = 7

[cache]
enabled = true
default_ttl = "5m"

# Feature flags defined as an inline table
features = { new_ui = true, dark_mode = false, experimental_search = true }

[thresholds]
cpu_warning = 80.5
memory_critical = 95.0 