service:
  name: gofiggy-test-app
  port: 8090
logging:
  level: "info"
  enabled_plugins:
    - request_logger
    - cors_handler
  request_timeout_seconds: 30
  debug_mode: false
  optional_component: null
external_service:
  url: https://api.example.com/v1
  api_key: '{{ getenv "EXTERNAL_API_KEY" }}'
